JMS/JMS/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('article/', include('article.urls', namespace='article')),
    path('', include('home.urls', namespace='home')),
]

JMS/article/urls.py
from django.urls import path, re_path
from .views import index, single_blog

app_name = 'article'
urlpatterns = [
  path('', index.as_view(), name='index'),
  re_path(r'^(?P<year>[\w-]+)/(?P<month>[\w-]+)/(?P<day>[\w-]+)/(?P<articleSlug>[\w-]+)/', single_blog.as_view()),
]

JMS/home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
  path('', views.index.as_view(), name='index'),
  path('kurs/', views.kurs.as_view(), name='kurs'),
  path('kontak/', views.contact.as_view(), name='contact'),
]

JMS/article/models.py
from django.db import models
from django.utils.text import slugify

# Create your models here.

class Article(models.Model):
  title = models.CharField(verbose_name='Title', max_length=255, default='')
  thumbnail = models.ImageField(verbose_name='Thumbnail', upload_to='static/blog/assets/img/static/thumbnail/%Y/%m/%d', default='')
  content = models.TextField(verbose_name='Content', max_length=100000, default='')
  published = models.DateTimeField(editable=True)
  updated = models.DateTimeField(auto_now=True)
  slug = models.SlugField(editable=False, blank=True)

  class Meta:
    verbose_name_plural = 'Artikel'

  def save(self):
    self.slug = slugify(self.title)
    super(Article, self).save()

  def __str__(self):
    return f'{self.title}'

JMS/home/models.py
from django.db import models
from solo.models import SingletonModel

# Create your models here.

class Carousel(models.Model):
  title = models.CharField(verbose_name='Judul Carousel', max_length=255, default='')
  desc = models.TextField(verbose_name='Deskripsi Carousel', help_text='masukkan deskripsi yang singkat padat dan jelas (usahakan tidak terlalu panjang)', max_length=255, default='')
  background = models.ImageField(verbose_name='Foto Background', upload_to='static/assets/images/carousel/%Y/%m/%d', default='')

  def __str__(self):
    return f'{self.title}'

class Data_Angka(SingletonModel):

  project = models.IntegerField(verbose_name='Jumlah Projek yang Terlaksana', default='0')
  employee = models.IntegerField(verbose_name='Jumlah Karyawan', default='0')
  client = models.IntegerField(verbose_name='Jumlah Client', default='0')
  experience = models.IntegerField(verbose_name='Tahun Pengalaman', help_text='sudah berapa tahun pengalaman di bidang ini', default='0')

  class Meta:
    verbose_name = 'Data Untuk Home'

  def __str__(self):
    return 'Data'

class Client(models.Model):
  name = models.CharField(verbose_name='Nama Perusahaan Client', default='', blank=True, max_length=255)
  logo = models.ImageField(verbose_name='Logo Client', upload_to='static/assets/images/clients/%Y/%m/%d', default='')

  def __str__(self):
    return f'{self.name}'

class Social_Media(models.Model):
  link = models.URLField(verbose_name='Link Social Media', max_length=500, default='')
  logo = models.CharField(verbose_name='Logo Social Media', help_text='sumber logo dari https://fontawesome.com/v4.7/icons/ contoh: <i class="fa fa-instagram" aria-hidden="true"></i>', max_length=255, default='')

JMS/article/views.py
from django.shortcuts import render, redirect
from django.views.generic import TemplateView
from django.utils.timezone import localtime
from home.models import Social_Media
from .models import Article

# Create your views here.

class index(TemplateView):

  def __init__(self):
    self.context = {
      'title': 'Artikel | JMS Logistik | PT Jasa Moda Solusi',
      'social_media': Social_Media.objects.all(),
      'articles': None}

  def get(self, request):
    self.context['articles'] = Article.objects.order_by('-published')
    
    return render(request, 'article/index.html', self.context)

class single_blog(TemplateView):

  def __init__(self):
    self.context = {
      'title': '',
      'social_media': Social_Media.objects.all(),
      'article': None}
    self.backredirect = '../../../../'
  
  def get(self, request, *args, **kwargs):
    articles = Article.objects.filter(slug=kwargs.get('articleSlug'))

    def filterArticles(x):
      articles_time = localtime(x.published)
      if articles_time.year == int(kwargs.get('year')) and articles_time.month == int(kwargs.get('month')) and articles_time.day == int(kwargs.get('day')):
        return True
      else:
        return False

    articles = filter(filterArticles, articles)
    articles = list(articles)

    if not articles:
      return redirect(self.backredirect)

    self.context['title'] = f'{articles[0].title} - Artikel | JMS Logistik | PT Jasa Moda Solusi'
    self.context['article'] = articles[0]

    return render(request, 'article/single_article/index.html', self.context)

JMS/home/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
import requests
from article.models import Article
from . import models

# Create your views here.

class index(TemplateView):

  def __init__(self):
    self.context = {
      'title': 'JMS Logistik | PT Jasa Moda Solusi',
      'carousel': models.Carousel.objects.all(),
      'data_home': models.Data_Angka.objects.all()[0],
      'articles': Article.objects.order_by('-published')[0:3],
      'clients': models.Client.objects.all(),
      'social_media': models.Social_Media.objects.all(),
      'home_kurs': [],
      'kurs': []
    }

  def get(self, request):
    url = 'https://api.exchangerate.host/latest?base=IDR&amount=1'
    response = requests.get(url)
    data_list = list(response.json()['rates'].items())

    for i in data_list:
      if i[1] != 0:
        self.context['kurs'].append((i[0], 1 / i[1]))

      if i[0] == 'USD':
        self.context['home_kurs'].append((i[0], 1 / i[1]))
      elif i[0] == 'EUR':
        self.context['home_kurs'].append((i[0], 1 / i[1]))
      elif i[0] == 'CNY':
        self.context['home_kurs'].append((i[0], 1 / i[1]))
      elif i[0] == 'JPY':
        self.context['home_kurs'].append((i[0], 1 / i[1]))
      elif i[0] == 'AUD':
        self.context['home_kurs'].append((i[0], 1 / i[1]))
      elif i[0] == 'SGD':
        self.context['home_kurs'].append((i[0], 1 / i[1]))
      elif i[0] == 'MYR':
        self.context['home_kurs'].append((i[0], 1 / i[1]))

    return render(request, 'home/index.html', self.context)

class kurs(TemplateView):

  def __init__(self):
    self.context = {
      'title': 'Kurs | JMS Logistik | PT Jasa Moda Solusi',
      'social_media': models.Social_Media.objects.all(),
      'kurs': [],
      'kurs_date': None
    }

  def get(self, request):
    url = 'https://api.exchangerate.host/latest?base=IDR&amount=1'
    response = requests.get(url)
    self.context['kurs_date'] = response.json()['date']
    data_list = list(response.json()['rates'].items())

    for i in data_list:
      if i[1] != 0:
        self.context['kurs'].append((i[0], 1 / i[1]))
    
    return render(request, 'home/kurs/index.html', self.context)

class contact(TemplateView):
  
  def __init__(self):
    self.context = {
      'title': 'Kontak | JMS Logistik | PT Jasa Moda Solusi'
    }

  def get(self, request):
    return render(request, 'home/contact/index.html', self.context)

JMS/article/templates/article/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="{% static 'assets/images/logo/logo-JMS.png' %}" rel="icon">
  <title>{{ title }}</title>
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Barlow:400,500,600,700%7cRoboto:400,500,700&display=swap">
  <link rel="stylesheet" href="{% static 'assets/css/libraries.css' %}">
  <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
</head>
<body>
  
  <div class="wrapper">
    <div class="preloader">
      <div class="loading"><span></span></div>
    </div>

    {% include 'includes/header.html' %}

    <section class="article-grid pb-5">
      <div class="container">
        <div class="row">
          <div class="col-sm-12 col-md-12 col-lg-6 offset-lg-3">
            <div class="heading text-center mb-50">
              <h2 class="section_title">Artikel Terkini</h2>
            </div>
          </div>
        </div>
        <div class="row">
          {% block articles %}{% endblock articles %}
        </div>
      </div>
    </section>

    {% include 'includes/footer.html' %}
  </div>

  <script src="{% static 'assets/js/jquery-3.5.1.min.js' %}"></script>
  <script src="{% static 'assets/js/plugins.js' %}"></script>
  <script src="{% static 'assets/js/main.js' %}"></script>
</body>
</html>

JMS/article/templates/article/index.html
{% extends 'article/base.html' %}
{% load static %}

{% block articles %}
{% for article in articles %}
<div class="col-sm-12 col-md-6 col-lg-4">
  <div class="article-item">
    <div class="article__img">
      <a href="{{ article.published | date:'Y/m/d' }}/{{ article.slug }}">
        <img src="{{ article.thumbnail.url }}" alt="{{ article.title }} thumbnail">
      </a>
    </div>
    <div class="article__content">
      <h4 class="article__title"><a href="{{ article.published | date:'Y/m/d' }}/{{ article.slug }}">{{ article.title }}</a></h4>
      <span class="article__meta-date">{{ article.published | date:'M d, Y' }}</span>
      <p class="article__desc">{{ article.content | striptags | truncatechars:200 }}</p>
      <a href="{{ article.published | date:'Y/m/d' }}/{{ article.slug }}" class="btn btn__secondary btn__link">
        <span>Selengkapnya</span>
        <i class="icon-arrow-right"></i>
      </a>
    </div>
  </div>
</div>
{% endfor %}
{% endblock articles %}

JMS/article/templates/article/single_article/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="{% static 'assets/images/logo/logo-JMS.png' %}" rel="icon">
  <title>{{ title }}</title>
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Barlow:400,500,600,700%7cRoboto:400,500,700&display=swap">
  <link rel="stylesheet" href="{% static 'assets/css/libraries.css' %}">
  <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
</head>
<body>
  
  <div class="wrapper">
    <div class="preloader">
      <div class="loading"><span></span></div>
    </div>

    {% include 'includes/header.html' %}

    <section class="article_single_container">
      <div class="container">
        <div class="row">
          <div class="col-12 col-lg-8">
            {% block article %}{% endblock article %}
          </div>
          <div class="col-12 col-lg-4">
            {% block side %}{% endblock side %}
          </div>
        </div>
      </div>
    </section>

    {% include 'includes/footer.html' %}
  </div>

  <script src="{% static 'assets/js/jquery-3.5.1.min.js' %}"></script>
  <script src="{% static 'assets/js/plugins.js' %}"></script>
  <script src="{% static 'assets/js/main.js' %}"></script>
  <script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-61cafc8b0c4afc71"></script>
</body>
</html>

JMS/article/templates/article/single_article/index.html
{% extends 'article/single_article/base.html' %}
{% load static %}

{% block article %}
<div class="article-item">
  <div class="article_single__img">
    <img src="{{ article.thumbnail.url }}" alt="{{ article.title }} thumbnail">
  </div>
  <div class="article__content">
    <h4 class="article__title">{{ article.title }}</h4>
    <span class="article__meta-date">{{ article.published | date:'M d, Y' }}</span>
    <p class="article__desc">{{ article.content | safe }}</p>
  </div>
</div>
{% endblock article %}

{% block side %}
<div class="row article_single_side">
  <div class="col-12 footer__widget footer__widget-newsletter">
    <h6 class="footer__widget-title">Newsletter</h6>
    <div class="footer__widget-content">
      <p>Sign up untuk mendapatkan informasi mengenai artikel terbaru dari kami.</p>
      <form class="widget__newsletter-form">
        <div class="form-group mb-0">
          <input type="text" class="form-control" placeholder="Alamat Email Anda">
          <button type="submit" class="btn btn__primary">
            <i class="icon-arrow-right"></i>
          </button>
        </div>
      </form>
    </div>
  </div>
  <div class="col-12">
    <center>
      <div class="addthis_inline_share_toolbox"></div>
    </center>
  </div>
</div>
{% endblock side %}

JMS/home/templates/home/base.html
{% load static %}
{% load kurs %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <meta name="description" content="PT Jasa Moda Solusi | JMS">
  <link href="{% static 'assets/images/logo/logo-JMS.png' %}" rel="icon">
  <title>{{ title }}</title>
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Barlow:400,500,600,700%7cRoboto:400,500,700&display=swap">
  <link rel="stylesheet" href="{% static 'assets/css/libraries.css' %}">
  <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
  <script type="text/javascript" id="zsiqchat">var $zoho=$zoho || {};$zoho.salesiq = $zoho.salesiq || {widgetcode: "2952cd77df79e3f1a768e123aae4ef702dec7fb39423b2a713a08cc15a2041721a2010ab7b6727677d37b27582c0e9c4", values:{},ready:function(){}};var d=document;s=d.createElement("script");s.type="text/javascript";s.id="zsiqscript";s.defer=true;s.src="https://salesiq.zoho.com/widget";t=d.getElementsByTagName("script")[0];t.parentNode.insertBefore(s,t);</script>
</head>
<body>
  <div class="wrapper">
    <div class="preloader">
      <div class="loading"><span></span></div>
    </div>

    {% include 'includes/header.html' %}

    {% block slider %}{% endblock slider %}

    {% block about %}{% endblock about %}

    {% block services %}{% endblock services %}

    {% block data_home %}{% endblock data_home %}

    {% block kurs %}{% endblock kurs %}
    
    {% block why %}{% endblock why %}
    
    {% block article %}{% endblock article %}

    {% block clients %}{% endblock clients %}

    {% include 'includes/footer.html' %}

    <button id="scrollTopBtn"><i class="fa fa-long-arrow-up"></i></button>
  </div>

  <script src="{% static 'assets/js/jquery-3.5.1.min.js' %}"></script>
  <script src="{% static 'assets/js/plugins.js' %}"></script>
  <script src="{% static 'assets/js/main.js' %}"></script>
</body>

</html>

JMS/home/templates/home/contact/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="{% static 'assets/images/logo/logo-JMS.png' %}" rel="icon">
  <title>{{ title }}</title>
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Barlow:400,500,600,700%7cRoboto:400,500,700&display=swap">
  <link rel="stylesheet" href="{% static 'assets/css/libraries.css' %}">
  <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
  <script type="text/javascript" id="zsiqchat">var $zoho=$zoho || {};$zoho.salesiq = $zoho.salesiq || {widgetcode: "2952cd77df79e3f1a768e123aae4ef702dec7fb39423b2a713a08cc15a2041721a2010ab7b6727677d37b27582c0e9c4", values:{},ready:function(){}};var d=document;s=d.createElement("script");s.type="text/javascript";s.id="zsiqscript";s.defer=true;s.src="https://salesiq.zoho.com/widget";t=d.getElementsByTagName("script")[0];t.parentNode.insertBefore(s,t);</script>
</head>
<body>

  <div class="wrapper">
    <div class="preloader">
      <div class="loading"><span></span></div>
    </div>

    
  </div>
  
  <script src="{% static 'assets/js/jquery-3.5.1.min.js' %}"></script>
  <script src="{% static 'assets/js/plugins.js' %}"></script>
  <script src="{% static 'assets/js/main.js' %}"></script>
</body>
</html>

JMS/home/templates/home/contact/index.html
{% extends 'home/contact/base.html' %}
{% load static %}

JMS/home/templates/home/kurs/index.html
{% load static %}
{% load kurs %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="{% static 'assets/images/logo/logo-JMS.png' %}" rel="icon">
  <title>{{ title }}</title>
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Barlow:400,500,600,700%7cRoboto:400,500,700&display=swap">
  <link rel="stylesheet" href="{% static 'assets/css/libraries.css' %}">
  <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
  <script type="text/javascript" id="zsiqchat">var $zoho=$zoho || {};$zoho.salesiq = $zoho.salesiq || {widgetcode: "2952cd77df79e3f1a768e123aae4ef702dec7fb39423b2a713a08cc15a2041721a2010ab7b6727677d37b27582c0e9c4", values:{},ready:function(){}};var d=document;s=d.createElement("script");s.type="text/javascript";s.id="zsiqscript";s.defer=true;s.src="https://salesiq.zoho.com/widget";t=d.getElementsByTagName("script")[0];t.parentNode.insertBefore(s,t);</script>
</head>
<body>
  {% include 'includes/header.html' %}
  <div class="preloader">
    <div class="loading"><span></span></div>
  </div>

  <section class="kurs">
    <div class="container">
      <div class="row">
        <div class="col-sm-12 col-md-12 col-lg-6 offset-lg-3">
          <div class="heading text-center mb-50">
            <h2 class="section_title">Kurs - Exchange Rate</h2>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-12 kurs_date">
          <span>Terakhir diupdate: {{ kurs_date }}</span>
        </div>
        <table class="table table-striped text-center">
          <thead>
            <tr>
              <th scope="col" class="kurs_header">Mata Uang</th>
              <th scope="col" class="kurs_header">Kurs Indonesia</th>
            </tr>
          </thead>
          <tbody>
            {% for i in kurs %}
            <tr>
              <td>{{i|exrate_display:'country'}}</td>
              <td>{{i|exrate_display:'rate'}}</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </section>

  {% include 'includes/footer.html' %}

  <script src="{% static 'assets/js/jquery-3.5.1.min.js' %}"></script>
  <script src="{% static 'assets/js/plugins.js' %}"></script>
  <script src="{% static 'assets/js/main.js' %}"></script>
</body>
</html>

JMS/templates/includes/footer.html
{% load static %}
<footer class="footer">
  <div class="footer-top">
    <div class="container">
      <div class="row">
        <div class="col-sm-12 col-md-8 col-lg-4 col-xl-4 footer__widget footer__widget-about">
          <div class="footer__widget-content">
            <img src="{% static 'assets/images/logo/logo-JMS.png' %}" width="97px" height="49px" alt="logo" class="mb-30">
            <p class="mb-20">PT. JASA MODA SOLUSI adalah perusahaan yang bergerak pada bidang Jasa baik konsultan Jasa Konstruksi dan Jasa Logistics</p>
            <ul class="social__icons list-unstyled">
              {% for item in social_media %}
              <li><a href="{{ item.link }}" target="_blank">{{item.logo | safe}}</a></li>
              {% endfor %}
            </ul>
          </div>
        </div>
        <div class="col-6 col-sm-6 col-md-4 col-lg-2 col-xl-2 footer__widget footer__widget-nav">
          <h6 class="footer__widget-title">Services</h6>
          <div class="footer__widget-content">
            <nav>
              <ul class="list-unstyled">
                <li><a href="#">Construction Manage</a></li>
                <li><a href="#">Construction Consultants</a></li>
                <li><a href="#">Architecture & Building</a></li>
                <li><a href="#">Home Renovations</a></li>
                <li><a href="#">Tiling & Painiting</a></li>
                <li><a href="#">Interior Design</a></li>
              </ul>
            </nav>
          </div>
        </div>
        <div class="col-sm-6 col-md-12 col-lg-6 col-xl-6 footer__widget footer__widget-newsletter">
          <h6 class="footer__widget-title">Newsletter</h6>
          <div class="footer__widget-content">
            <p>Sign up untuk mendapatkan informasi mengenai artikel terbaru dari kami.</p>
            <form class="widget__newsletter-form">
              <div class="form-group mb-0">
                <input type="text" class="form-control" placeholder="Alamat Email Anda">
                <button type="submit" class="btn btn__primary">
                  <i class="icon-arrow-right"></i>
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="footer-bottom">
    <div class="container">
      <div class="row align-items-center">
        <div class="col-sm-12 col-md-12 col-lg-12 d-flex flex-wrap justify-content-center">
          <p class="mb-0 color-white"> &copy; 2021 PT Jasa Moda Solusi</p>
        </div>
      </div>
    </div>
  </div>
</footer>

JMS/templates/includes/header.html
{% load static %}
<div class="block-80 d-none" style="height: 80px;"></div>
<header class="header header-light header-layout2">
  <nav class="navbar navbar-expand-lg sticky-navbar fixed-navbar">
    <div class="container">
      <a class="navbar-brand" href="{% url 'home:index' %}">
        <img src="{% static 'assets/images/logo/logo-JMS.png' %}" width="97px" height="49px" alt="logo">
        {% comment %} <img src="{% static 'assets/images/logo/logo-teks-JMS.png' %}" class="ml-1" height="20px" alt="logo"> {% endcomment %}
      </a>
      <button class="navbar-toggler" type="button">
        <span class="menu-lines"><span></span></span>
      </button>
      <div class="collapse navbar-collapse" id="mainNavigation">
        <ul class="navbar-nav ml-auto">
          <li class="nav__item with-dropdown">
            <a href="{% url 'home:index' %}" class="nav__item-link {% if request.path == '/' %}active{% endif %}">Home</a>
          </li>
          <li class="nav__item with-dropdown">
            <a href="{% url 'home:index' %}#tentang_kami" class="nav__item-link">Tentang Kami</a>
          </li>
          <li class="nav__item with-dropdown">
            <a href="{% url 'home:index' %}#services" class="nav__item-link">Our Services</a>
          </li>
          <li class="nav__item with-dropdown">
            <a href="{% url 'article:index' %}" class="nav__item-link {% if 'article' in request.path %}active{% endif %}">Artikel</a>
          </li>
          <li class="nav__item">
            <a href="https://wa.me/628111688882" target="_blank" class="nav__item-link">Kontak</a>
          </li>
          {% comment %} <li class="nav__item with-dropdown">
            <a href="about-us.html" class="dropdown-toggle nav__item-link">Company</a>
            <i class="fa fa-angle-down" data-toggle="dropdown"></i>
            <ul class="dropdown-menu">
              <li class="nav__item"><a href="about-us.html" class="nav__item-link">About Us</a></li>
              <!-- /.nav-item -->
              <li class="nav__item"><a href="core-values.html" class="nav__item-link">core values</a></li>
              <!-- /.nav-item -->
              <li class="nav__item"><a href="leadership-team.html" class="nav__item-link">Leadership Team</a></li>
              <!-- /.nav-item -->
              <li class="nav__item"><a href="pricing.html" class="nav__item-link">Pricing & Plans</a></li>
              <!-- /.nav-item -->
              <li class="nav__item"><a href="faqs.html" class="nav__item-link">Help & FAQs</a></li>
              <!-- /.nav-item -->
              <li class="nav__item"><a href="careers.html" class="nav__item-link">careers</a></li>
              <!-- /.nav-item -->
            </ul><!-- /.dropdown-menu -->
          </li><!-- /.nav-item --> {% endcomment %}
          {% comment %} <li class="nav__item with-dropdown">
            <a href="services.html" class="dropdown-toggle nav__item-link">Services</a>
            <i class="fa fa-angle-down" data-toggle="dropdown"></i>
            <ul class="dropdown-menu">
              <li class="nav__item"><a href="services-single-service.html" class="nav__item-link">Construction
                  Manage</a></li>
              <!-- /.nav-item -->
              <li class="nav__item"><a href="services-single-service.html" class="nav__item-link">Construction
                  Consultants</a></li>
              <!-- /.nav-item -->
              <li class="nav__item"><a href="services-single-service.html" class="nav__item-link">Architecture &
                  Building</a></li>
              <!-- /.nav-item -->
              <li class="nav__item"><a href="services-single-service.html" class="nav__item-link">Home
                  Renovations</a></li>
              <!-- /.nav-item -->
              <li class="nav__item"><a href="services-single-service.html" class="nav__item-link">Tiling &
                  Painiting</a></li>
              <!-- /.nav-item -->
              <li class="nav__item"><a href="services-single-service.html" class="nav__item-link">Interior
                  Design</a></li>
              <!-- /.nav-item -->
            </ul><!-- /.dropdown-menu -->
          </li><!-- /.nav-item --> {% endcomment %}
          {% comment %} <li class="nav__item with-dropdown">
            <a href="projects-grid.html" class="dropdown-toggle nav__item-link">Projects</a>
            <i class="fa fa-angle-down" data-toggle="dropdown"></i>
            <ul class="dropdown-menu">
              <li class="nav__item"><a href="projects-grid.html" class="nav__item-link">projects grid</a></li>
              <!-- /.nav-item -->
              <li class="nav__item"><a href="projects-standard.html" class="nav__item-link">projects standard</a>
              </li><!-- /.nav-item -->
              <li class="nav__item"><a href="projects-carousel.html" class="nav__item-link">projects carousel</a>
              </li><!-- /.nav-item -->
              <li class="nav__item"><a href="projects-single-project.html" class="nav__item-link">projects
                  single</a></li><!-- /.nav-item -->
            </ul><!-- /.dropdown-menu -->
          </li><!-- /.nav-item --> {% endcomment %}
          {% comment %} <li class="nav__item with-dropdown">
            <a href="blog.html" class="dropdown-toggle nav__item-link">News & Media</a>
            <i class="fa fa-angle-down" data-toggle="dropdown"></i>
            <ul class="dropdown-menu">
              <li class="nav__item">
                <a href="blog.html" class="nav__item-link">Blog Grid</a>
              </li><!-- /.nav-item -->
              <li class="nav__item">
                <a href="blog-single-post.html" class="nav__item-link">Single Blog Post</a>
              </li><!-- /.nav-item -->
            </ul><!-- /.dropdown-menu -->
          </li><!-- /.nav-item --> {% endcomment %}
        </ul><!-- /.navbar-nav -->
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container -->
  </nav><!-- /.navabr -->
</header><!-- /.Header -->